-   id: rust
    name: rust
    language: python
    entry: ./run.py 'rust.pre-commit-config.yaml'
    verbose: true

-   id: python
    name: python
    language: python
    entry: ./run.py 'python.pre-commit-config.yaml'
    verbose: true
