-   id: rust
    name: rust
    language: script
    entry: ./run.py rust.pre-commit-config.yaml
    args: ['']
    verbose: true
    require_serial: true  # Workaround to run only once with all filenames

-   id: python
    name: python
    language: script
    entry: ./run.py python.pre-commit-config.yaml
    args: ['']
    verbose: true
    require_serial: true  # Workaround to run only once with all filenames

-   id: general
    name: general
    language: script
    entry: ./run.py general.pre-commit-config.yaml
    args: ['']
    verbose: true
    require_serial: true  # Workaround to run only once with all filenames
