-   id: docker-image-pin
    name: docker-image-pin
    description: Checks if Docker images are properly pinned in docker-compose.yml and Dockerfile files
    entry: pre-commit-hooks docker
    language: python
    types_or: [yaml, dockerfile]
    files: docker-compose\.ya?ml$|Dockerfile$

-   id: gha-pin
    name: gha-pin
    description: Checks if Docker images are properly pinned in docker-compose.yml and Dockerfile files
    entry: pre-commit-hooks gha
    language: python
    types: [yaml]

-   id: shfuncdecfmt
    name: shfuncdecfmt
    description: Shell function declaration formatter
    entry: pre-commit-hooks shfuncdecfmt
    language: python
    types: [shell]

-   id: pre-commit-additional-dependencies
    name: pre-commit-additional-dependencies
    description: Sync pre-commit additional_dependencies with uv.lock
    entry: pre-commit-hooks pcad
    language: python
    pass_filenames: false
    files: ^uv.lock$|^.pre-commit-config.yaml$
