-   id: rust
    name: rust
    language: script
    entry: ./run 'rust.pre-commit-config.yaml'
    verbose: true

-   id: python
    name: python
    language: script
    entry: ./run 'python.pre-commit-config.yaml'
    verbose: true
