name: Release

on:
  push:
    tags:
      - v*

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        run: gh release create "${tag}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
